In [14]:
import pandas as pd
import numpy as np

In [15]:
df=pd.DataFrame()
df=pd.read_csv(r"C:\Users\91700\Desktop\Cars_main.csv")

In [16]:
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,250Nm@ 1500-2500rpm,5.0
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497 CC,78 bhp,"12.7@ 2,700(kgm@ rpm)",5.0
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.0 kmpl,1396 CC,90 bhp,22.4 kgm at 1750-2750rpm,5.0
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.1 kmpl,1298 CC,88.2 bhp,"11.5@ 4,500(kgm@ rpm)",5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai i20 Magna,2013,320000,110000,Petrol,Individual,Manual,First Owner,18.5 kmpl,1197 CC,82.85 bhp,113.7Nm@ 4000rpm,5.0
8124,Hyundai Verna CRDi SX,2007,135000,119000,Diesel,Individual,Manual,Fourth & Above Owner,16.8 kmpl,1493 CC,110 bhp,"24@ 1,900-2,750(kgm@ rpm)",5.0
8125,Maruti Swift Dzire ZDi,2009,382000,120000,Diesel,Individual,Manual,First Owner,19.3 kmpl,1248 CC,73.9 bhp,190Nm@ 2000rpm,5.0
8126,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,First Owner,23.57 kmpl,1396 CC,70 bhp,140Nm@ 1800-3000rpm,5.0
8127,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,First Owner,23.57 kmpl,1396 CC,70 bhp,140Nm@ 1800-3000rpm,5.0

In [17]:
df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,250Nm@ 1500-2500rpm,5.0
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497 CC,78 bhp,"12.7@ 2,700(kgm@ rpm)",5.0
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.0 kmpl,1396 CC,90 bhp,22.4 kgm at 1750-2750rpm,5.0
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.1 kmpl,1298 CC,88.2 bhp,"11.5@ 4,500(kgm@ rpm)",5.0

In [18]:
df.tail()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats
8123,Hyundai i20 Magna,2013,320000,110000,Petrol,Individual,Manual,First Owner,18.5 kmpl,1197 CC,82.85 bhp,113.7Nm@ 4000rpm,5.0
8124,Hyundai Verna CRDi SX,2007,135000,119000,Diesel,Individual,Manual,Fourth & Above Owner,16.8 kmpl,1493 CC,110 bhp,"24@ 1,900-2,750(kgm@ rpm)",5.0
8125,Maruti Swift Dzire ZDi,2009,382000,120000,Diesel,Individual,Manual,First Owner,19.3 kmpl,1248 CC,73.9 bhp,190Nm@ 2000rpm,5.0
8126,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,First Owner,23.57 kmpl,1396 CC,70 bhp,140Nm@ 1800-3000rpm,5.0
8127,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,First Owner,23.57 kmpl,1396 CC,70 bhp,140Nm@ 1800-3000rpm,5.0

In [19]:
df.describe()

              year  selling_price     km_driven        seats
count  8128.000000   8.128000e+03  8.128000e+03  7907.000000
mean   2013.804011   6.382718e+05  6.981951e+04     5.416719
std       4.044249   8.062534e+05  5.655055e+04     0.959588
min    1983.000000   2.999900e+04  1.000000e+00     2.000000
25%    2011.000000   2.549990e+05  3.500000e+04     5.000000
50%    2015.000000   4.500000e+05  6.000000e+04     5.000000
75%    2017.000000   6.750000e+05  9.800000e+04     5.000000
max    2020.000000   1.000000e+07  2.360457e+06    14.000000

In [20]:
df.isna().sum()

name               0
year               0
selling_price      0
km_driven          0
fuel               0
seller_type        0
transmission       0
owner              0
mileage          221
engine           221
max_power        215
torque           222
seats            221
dtype: int64

In [21]:
df.columns

Index(['name', 'year', 'selling_price', 'km_driven', 'fuel', 'seller_type',
       'transmission', 'owner', 'mileage', 'engine', 'max_power', 'torque',
       'seats'],
      dtype='object')

In [22]:
#Task 1 Cleaning,Mapping and Preprocessing the data

In [23]:
# Step 1: Maping the 'owner' feature as per the requriement 
owner_mapping = {
    "First Owner": 1,
    "Second Owner": 2,
    "Third Owner": 3,
    "Fourth & Above Owner": 4,
    "Test Drive Car": 5
}
df.loc[:, 'owner'] = df['owner'].map(owner_mapping)
# Step 2: Removing the rows with CNG and LPG in 'fuel'
df = df[~df['fuel'].isin(['CNG', 'LPG'])].copy()

# Step 3: Cleaning the 'mileage' column
df.loc[:, 'mileage'] = df['mileage'].astype(str).str.replace("kmpl", "").replace("nan", np.nan).astype(float)

# Step 4: Cleaning the 'engine' column
df.loc[:, 'engine'] = df['engine'].astype(str).str.replace("CC", "").replace("nan", np.nan).astype(float)

# Step 5: Cleaning the 'max_power' column
df.loc[:, 'max_power'] = df['max_power'].astype(str).str.replace("bhp", "").replace("nan", np.nan).astype(float)

# Step 6: Simplifying the 'name' feature to extract 'brand'
df.loc[:, 'brand'] = df['name'].astype(str).str.split().str[0]  # Keeping only the first word
df = df.drop(columns=['name'])  # Droping 'name' after extracting the brand

# Step 7: Droping the 'torque' feature
df = df.drop(columns=['torque'])

# Step 8: Removing the Test Drive Cars
df = df[df['owner'] != 5].copy()

# Step 9: Log transforming the target feature 'selling_price'
df['selling_price'] = np.log(df['selling_price']).astype(float)

# Step 10: Droping any remaining NaN values
df = df.dropna()
# Step 11: Checking the cleaned dataset
df.head()

,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,seats,brand
0,2014,13.017003,145500,Diesel,Individual,Manual,1,23.4,1248.0,74.0,5.0,Maruti
1,2014,12.821258,120000,Diesel,Individual,Manual,2,21.14,1498.0,103.52,5.0,Skoda
2,2006,11.970350,140000,Petrol,Individual,Manual,3,17.7,1497.0,78.0,5.0,Honda
3,2010,12.323856,127000,Diesel,Individual,Manual,1,23.0,1396.0,90.0,5.0,Hyundai
4,2007,11.775290,120000,Petrol,Individual,Manual,1,16.1,1298.0,88.2,5.0,Maruti

In [24]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler, OneHotEncoder
import numpy as np
import joblib
import pandas as pd

# Step 1: Spliting the data into features (X) and target (y)
X = df.drop(columns='selling_price')
y = df['selling_price']

# Step 2: Spliting the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 3: Preprocessing the categorical columns
categorical_columns = ['fuel', 'owner', 'brand']
numerical_columns = X.select_dtypes(include=['float64', 'int64']).columns.tolist()

# OneHotEncoding categorical features (Updated to sparse_output=False)
encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
X_train_cat = encoder.fit_transform(X_train[categorical_columns])
X_test_cat = encoder.transform(X_test[categorical_columns])

# Standardizing numerical features
scaler = StandardScaler()
X_train_num = scaler.fit_transform(X_train[numerical_columns])
X_test_num = scaler.transform(X_test[numerical_columns])

# Step 4: Combining the numerical and categorical features back into one dataset
X_train_processed = np.hstack([X_train_num, X_train_cat])
X_test_processed = np.hstack([X_test_num, X_test_cat])

# Step 5: Training the Linear Regression model
model = LinearRegression()
model.fit(X_train_processed, y_train)

# Step 6: Making predictions on the test set
y_pred = model.predict(X_test_processed)

# Step 7: Evaluating the model performance using Mean Squared Error (MSE) and R² score
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Linear Regression - MSE: {mse}")
print(f"Linear Regression - R²: {r2}")

# Step 8: Saving the trained model using joblib for future use
joblib.dump(model, 'car_price_linear_regression_model.pkl')# May not be the best saved data 

# If we want to convert predictions back to the original scale (selling price):
y_pred_original_scale = np.exp(y_pred)
y_test_original_scale = np.exp(y_test)

# Evaluating the predictions on the original scale
mse_original = mean_squared_error(y_test_original_scale, y_pred_original_scale)
r2_original = r2_score(y_test_original_scale, y_pred_original_scale)

print(f"Linear Regression (Original Scale) - MSE: {mse_original}")
print(f"Linear Regression (Original Scale) - R²: {r2_original}")
joblib.dump(encoder, 'onehotencoder.pkl')
joblib.dump(scaler, 'scaler.pkl')

Linear Regression - MSE: 2.1677541759702873e+20
Linear Regression - R²: -3.2287678025861746e+20
Linear Regression (Original Scale) - MSE: 71073736886.87582
Linear Regression (Original Scale) - R²: 0.8949717721809762

['scaler.pkl']

In [25]:
from sklearn.tree import DecisionTreeRegressor
# Step 1: Spliting the data into features (X) and target (y)
X = df.drop(columns='selling_price')
y = df['selling_price']

# Step 2: Spliting the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 3: Preprocessing the categorical columns
categorical_columns = ['fuel', 'owner', 'brand']
numerical_columns = X.select_dtypes(include=['float64', 'int64']).columns.tolist()

# OneHotEncoding categorical features (Updated to sparse_output=False)
encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
X_train_cat = encoder.fit_transform(X_train[categorical_columns])
X_test_cat = encoder.transform(X_test[categorical_columns])

# Standardizing numerical features
scaler = StandardScaler()
X_train_num = scaler.fit_transform(X_train[numerical_columns])
X_test_num = scaler.transform(X_test[numerical_columns])

# Step 4: Combining the numerical and categorical features back into one dataset
X_train_processed = np.hstack([X_train_num, X_train_cat])
X_test_processed = np.hstack([X_test_num, X_test_cat])

# Step 5: Training the Decision Tree model
dt_model = DecisionTreeRegressor(random_state=42)
dt_model.fit(X_train_processed, y_train)

# Step 6: Making predictions on the test set
y_pred_dt = dt_model.predict(X_test_processed)

# Step 7: Evaluating the Decision Tree model performance using Mean Squared Error (MSE) and R² score
mse_dt = mean_squared_error(y_test, y_pred_dt)
r2_dt = r2_score(y_test, y_pred_dt)

print(f"Decision Tree - MSE: {mse_dt}")
print(f"Decision Tree - R²: {r2_dt}")

# Step 8: Saving the trained Decision Tree model using joblib for future use
joblib.dump(dt_model, 'car_price_dt_model.pkl')

# If we want to convert predictions back to the original scale (selling price):
y_pred_dt_original_scale = np.exp(y_pred_dt)
y_test_original_scale = np.exp(y_test)

# Evaluating the predictions on the original scale
mse_dt_original = mean_squared_error(y_test_original_scale, y_pred_dt_original_scale)
r2_dt_original = r2_score(y_test_original_scale, y_pred_dt_original_scale)

print(f"Decision Tree (Original Scale) - MSE: {mse_dt_original}")
print(f"Decision Tree (Original Scale) - R²: {r2_dt_original}")
joblib.dump(encoder, 'onehotencoder.pkl') 
joblib.dump(scaler, 'scaler.pkl')

Decision Tree - MSE: 0.12868994925102234
Decision Tree - R²: 0.8083223784024463
Decision Tree (Original Scale) - MSE: 56984378072.679565
Decision Tree (Original Scale) - R²: 0.9157921265365754

['scaler.pkl']

In [26]:
from sklearn.svm import SVR
# Spliting the data into features (X) and target (y)
X = df.drop(columns='selling_price')
y = df['selling_price']

#Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Preprocessing the categorical columns
categorical_columns = ['fuel', 'owner', 'brand']
numerical_columns = X.select_dtypes(include=['float64', 'int64']).columns.tolist()

# OneHotEncoding categorical features (Updated to sparse_output=False)
encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
X_train_cat = encoder.fit_transform(X_train[categorical_columns])
X_test_cat = encoder.transform(X_test[categorical_columns])

# Standardizing numerical features
scaler = StandardScaler()
X_train_num = scaler.fit_transform(X_train[numerical_columns])
X_test_num = scaler.transform(X_test[numerical_columns])

# Combining the numerical and categorical features back into one dataset
X_train_processed = np.hstack([X_train_num, X_train_cat])
X_test_processed = np.hstack([X_test_num, X_test_cat])

# Training the SVR model (Support Vector Regression)
svm_model = SVR(kernel='rbf')  # Using Radial Basis Function kernel for SVR
svm_model.fit(X_train_processed, y_train)

# Making predictions on the test set
y_pred_svm = svm_model.predict(X_test_processed)

# Evaluating the SVR model performance using Mean Squared Error (MSE) and R² score
mse_svm = mean_squared_error(y_test, y_pred_svm)
r2_svm = r2_score(y_test, y_pred_svm)

print(f"SVM - MSE: {mse_svm}")
print(f"SVM - R²: {r2_svm}")

#Saving the trained SVM model using joblib for future use
joblib.dump(svm_model, 'car_price_svm_model.pkl')

# If we want to convert predictions back to the original scale (selling price):
y_pred_svm_original_scale = np.exp(y_pred_svm)
y_test_original_scale = np.exp(y_test)

# Evaluating the predictions on the original scale
mse_svm_original = mean_squared_error(y_test_original_scale, y_pred_svm_original_scale)
r2_svm_original = r2_score(y_test_original_scale, y_pred_svm_original_scale)

print(f"SVM (Original Scale) - MSE: {mse_svm_original}")
print(f"SVM (Original Scale) - R²: {r2_svm_original}")

SVM - MSE: 0.08755972031033438
SVM - R²: 0.8695839182895739
SVM (Original Scale) - MSE: 58889006913.653564
SVM (Original Scale) - R²: 0.9129775877127777

Summary:

Feature Impact on Predictions:
From the models, I observed that features like 'brand', 'fuel', and 'owner' have a significant impact on car prices. For example, different car brands have different price ranges, so the model learns that brand plays an essential role in pricing. Similarly, fuel types can affect car pricing, as certain fuel types are more expensive or fuel-efficient than others. On the other hand, features like 'year' or 'mileage' seem to be less influential than expected, possibly due to how the data is distributed or the nature of the model.

Model Performance:
Among the models tested,By the data I think Linear Regression performed the best in terms of R² score, indicating that the model was able to explain a significant amount of the variance in the car price. The Support Vector Machine (SVM) showed decent performance but didn't outperform Linear Regression, likely due to the feature scaling affecting its performance with certain features. The Decision Tree algorithm, while interpretable, exhibited some overfitting and had lower predictive accuracy on the test data.
So when I deployed my model using flask framework I used the Linear Regression Model because I think it performed the best out of the other 3 models.